package:
  name: pytorch-msssim
  {% set tagged_version = GIT_DESCRIBE_TAG|replace("v","")|replace("-", ".") %}
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
    {% set tagged_version = tagged_version %}
  {% endif %}

  version:
   {{tagged_version}}

source:
  git_url: ../

build:
  noarch: python
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: python -m pip install --no-deps --ignore-installed .
  string: {{PKG_BUILDNUM}}_h{{PKG_HASH}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  build:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - pytorch >=1.0

about:
  home: https://github.com/fynnbe/pytorch-msssim
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SSIM and MS-SSIM in pytorch'
  doc_url: https://github.com/fynnbe/pytorch-msssim
  dev_url: https://github.com/fynnbe/pytorch-msssim

test:
  imports:
    - pytorch_msssim
